import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/shared/header";
import localFont from "next/font/local";

const fontManrope = localFont({
  src: "/fonts/Manrope-VariableFont_wght.ttf",
  variable: "--font-manrope",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Audiophile-ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontManrope.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
